### ISSUE TITLE
some endpoints don't support setting volume

### ISSUE THREAD

**Issue by stormparticle** [stormparticle/spoticli#23]
```
spoticli ~$ volume 100
Traceback (most recent call last):
  File "/home/hlopez/.local/lib/python3.7/site-packages/cmd2/cmd2.py", line 1646, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
  File "/home/hlopez/.local/lib/python3.7/site-packages/cmd2/cmd2.py", line 2075, in onecmd
    stop = func(statement)
  File "/mnt/c/Users/hlopez/git-proj/spoticli/cli.py", line 552, in do_volume
    self.set_volume(new_vol)
  File "/mnt/c/Users/hlopez/git-proj/spoticli/cli.py", line 305, in set_volume
    self.sp_user.playback_volume(new_volume)
  File "/home/hlopez/.local/lib/python3.7/site-packages/tekore/_client/decor/__init__.py", line 41, in wrapper
    handle_errors(request, response)
  File "/home/hlopez/.local/lib/python3.7/site-packages/tekore/_client/decor/handle.py", line 43, in handle_errors
    raise error_cls(error_str, request=request, response=response)
tekore.Forbidden: Error in https://api.spotify.com/v1/me/player/volume?volume_percent=100:
403: Player command failed: Cannot control device volume
Not possible to remote control the device’s volume.

EXCEPTION of type 'Forbidden' occurred with message: 'Error in https://api.spotify.com/v1/me/player/volume?volume_percent=100:
403: Player command failed: Cannot control device volume
Not possible to remote control the device’s volume.
```

====================

will need to investigate. likely spotify api limitation, may need to account for it in the program

**Comment by stormparticle** [comment]
it's def a limitation of api and whatever endpoint we're working with. 
we'll fix it when we implement better exception handling in issue #28
