### ISSUE TITLE
error on playback status retrieval

### ISSUE THREAD

**Issue by stormparticle** [stormparticle/spoticli#28]
**Describe the bug**
trying to retrieve playback throws out errors
```
spoticli ~$ current
Traceback (most recent call last):
  File "/home/hlopez/.local/lib/python3.7/site-packages/cmd2/cmd2.py", line 1646, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
  File "/home/hlopez/.local/lib/python3.7/site-packages/cmd2/cmd2.py", line 2075, in onecmd
    stop = func(statement)
  File "/mnt/c/Users/hlopez/git-proj/spoticli/cli.py", line 402, in do_current
    time_stamp = self.generate_timestamp(song_data)
  File "/mnt/c/Users/hlopez/git-proj/spoticli/cli.py", line 88, in generate_timestamp
    dur_ms = self.ms_to_time(self.get_duration(song_data.item))
  File "/mnt/c/Users/hlopez/git-proj/spoticli/cli.py", line 159, in get_duration
    return song_data.duration_ms
AttributeError: 'NoneType' object has no attribute 'duration_ms'
EXCEPTION of type 'AttributeError' occurred with message: ''NoneType' object has no attribute 'duration_ms''
```

**To Reproduce**
1. while playback is inactive, assign an endpoint
1. don't start playback and instead retrieved now_playing

**Expected behavior**
playback status to be retrieved/shown or an endpoint error

**Desktop (please complete the following information):**
 - OS: Debian 10 Buster (via WSL on Win10)
 - Version 1.20.0706.dev / latest

**Comment by stormparticle** [comment]
here's the offending code
```
        except AttributeError:
            try:
                if(self.set_play_resume() == None):
                    return
            except:
                pass
```

issue is because ALL tekore exceptions are attribute errors, not just the 'no endpoint' exception, so of course this doesn't work.
will need to implement specific exception handling for this.

usually dealing with 3 types of errors here
1. session expiration/invalid (see issue #30)
1. trying to assign playback to non-active endpoint
1. trying to do something stupid like pausing a currently playing track or setting volume to -57

type 3 will need to be handled case-by-case based on whatever method it's used in and what it's supposed to do.

**Comment by stormparticle** [comment]
being worked on in issue #31, gotta fix exception handling
