### ISSUE TITLE
session expiration

### ISSUE THREAD

**Issue by stormparticle** [stormparticle/spoticli#30]
issue appeared after issue #29 was fixed; does not appear that automatic token refreshing is occurring.
this affects core functionality
tekore is responsible for retrieving new tokens as they expire. trying to use spotify api with expired tokens results in following:

```
Traceback (most recent call last):
  File "C:\Users\hlopez\AppData\Local\Programs\Python\Python38\lib\site-packages\cmd2\cmd2.py", line 2028, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
  File "C:\Users\hlopez\AppData\Local\Programs\Python\Python38\lib\site-packages\cmd2\cmd2.py", line 2458, in onecmd
    stop = func(statement)
  File "C:\Users\hlopez\git-proj\spoticli\cli.py", line 341, in do_diagnostics
    self.poutput(f'current user: \t{self.sp_user.current_user().display_name}')
  File "C:\Users\hlopez\AppData\Local\Programs\Python\Python38\lib\site-packages\tekore\_sender\client.py", line 79, in wrapper
    return post_func(request, response, *params)
  File "C:\Users\hlopez\AppData\Local\Programs\Python\Python38\lib\site-packages\tekore\_client\decor\__init__.py", line 20, in parse_response
    handle_errors(request, response)
  File "C:\Users\hlopez\AppData\Local\Programs\Python\Python38\lib\site-packages\tekore\_client\decor\handle.py", line 33, in handle_errors
    raise error_cls(error_str, request=request, response=response)
tekore.Unauthorised: Error in https://api.spotify.com/v1/me/:
401: The access token expired

EXCEPTION of type 'Unauthorised' occurred with message: 'Error in https://api.spotify.com/v1/me/:
401: The access token expired
```

**Comment by stormparticle** [comment]
looks like tekore added a builtin way of saving user creds/refresh info
this is probably better than my inhouse solution
will take a look over lunch

https://tekore.readthedocs.io/en/stable/reference/config.html#config

**Comment by stormparticle** [comment]
made some time and implemented tekore save load and deprecated my original implementation that uses pickle.
hopefully this should fix session preservation and expiration issues we're seeing
we'll find out in an hour.

**Comment by stormparticle** [comment]
nope

```
tekore.Unauthorised: Error in https://api.spotify.com/v1/me/player/currently-playing?additional_types=episode:
401: The access token expired

EXCEPTION of type 'Unauthorised' occurred with message: 'Error in https://api.spotify.com/v1/me/player/currently-playing?additional_types=episode:
401: The access token expired
```

i don't understand, we're returning and saving a refreshing token from tekore, why isn't it working?

**Comment by stormparticle** [comment]
yeah i was fucking up
i tried to save and pass an access token object instead of the actual refresh token.
whoops
we've completely switched over to tekore's auth method, just gotta clean up and fix up edge case handling during auth process.

**Comment by stormparticle** [comment]
feature parity with previous implementation. calling this fixed
